# Generated by Django 4.2.8 on 2023-12-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('table', models.JSONField(verbose_name='Таблица')),
                ('valid', models.BooleanField(blank=True, default=None, null=True, verbose_name='Валидна')),
                ('actual', models.BooleanField(default=False, verbose_name='Актуальная')),
            ],
            options={
                'verbose_name': 'Версия курсов',
                'verbose_name_plural': 'Версии курсов',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('errors', models.JSONField(verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
            },
        ),
        migrations.CreateModel(
            name='PricesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(verbose_name='Дата')),
                ('notion_id', models.CharField(max_length=100, verbose_name='ID страницы в Notion')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('full_price', models.PositiveIntegerField(verbose_name='Полная цена')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Процент скидки')),
                ('price_with_discount', models.PositiveIntegerField(verbose_name='Цена со скидкой')),
                ('price_per_month_with_discount', models.FloatField(verbose_name='Цена в месяц со скидкой')),
                ('price_per_month_without_discount', models.FloatField(verbose_name='Цена в месяц без скидки')),
            ],
            options={
                'verbose_name': 'Запись истории цен',
                'verbose_name_plural': 'Записи истории цен',
            },
        ),
    ]
