# Generated by Django 4.2.8 on 2023-12-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceshistory',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='priceshistory',
            name='full_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Полная цена'),
        ),
        migrations.AlterField(
            model_name='priceshistory',
            name='price_per_month_with_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в месяц со скидкой'),
        ),
        migrations.AlterField(
            model_name='priceshistory',
            name='price_per_month_without_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена в месяц без скидки'),
        ),
        migrations.AlterField(
            model_name='priceshistory',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
