version: '3.8'

services:

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  django_gunicorn:
    restart: always
    container_name: django_gunicorn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/proj
    env_file:
      - .env
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "-A md5"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

