version: '3.8'

services:

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  django_gunicorn:
    restart: always
    container_name: django_gunicorn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/proj/src/static
      - ./:/proj
    env_file:
      - .env
    ports:
      - "5000:5000"

volumes:
  static:

