# Generated by Django 4.2.2 on 2023-08-11 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен'),
        ),
    ]
