# Generated by Django 4.2.2 on 2023-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0002_promocode_deadline_alter_promocode_created_by_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='promocode',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='promocode',
        #     name='code',
        #     field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Промокод'),
        # ),
    ]
