# Generated by Django 4.2.2 on 2023-08-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0003_remove_promocode_id_alter_promocode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='code',
            new_name='name',
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['name'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
