# Generated by Django 4.2.2 on 2023-08-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0006_promocode_id_alter_promocode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='course_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
