# Generated by Django 4.2.2 on 2023-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0007_promocode_course_title_alter_promocode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocoderequest',
            name='response_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код ответа'),
        ),
    ]
