# Generated by Django 4.2.2 on 2023-11-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribedRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Processing', 'Обработка'), ('Processed', 'Обработано'), ('Error', 'Ошибка обработки')], default='Processing', max_length=20, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('speeches', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
            ],
            options={
                'verbose_name': 'Транскрибированная запись',
                'verbose_name_plural': 'Транскрибированные записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
