# Generated by Django 4.2.2 on 2023-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student_fio', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('course_hours', models.CharField(max_length=10)),
            ],
        ),
    ]
