# Generated by Django 4.2.2 on 2023-06-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20230628_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Удостоверение', 'verbose_name_plural': 'Удостоверения'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_hours',
            field=models.BigIntegerField(verbose_name='Длительность курса (часы)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(max_length=200, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_fio',
            field=models.CharField(max_length=100, verbose_name='ФИО студента'),
        ),
    ]
