# Generated by Django 4.2.2 on 2023-06-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('hours', models.BigIntegerField(verbose_name='Длительность (часы)')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course_hours',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.course', verbose_name='Курс'),
        ),
    ]
