# Generated by Django 4.2.2 on 2023-08-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_course_remove_certificate_course_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-pk'], 'verbose_name': 'Удостоверение', 'verbose_name_plural': 'Удостоверения'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
